apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
  namespace: mindmeld
  annotations:
    # Populated from Terraform output: api_pod_role_arn
    eks.amazonaws.com/role-arn: "${API_POD_ROLE_ARN}"
